[book]
authors = ["Robert Guthrie"]
language = "en"
multilingual = false
src = "src"
title = "Loomio User Manual"

[output.html]
no-section-label = true
edit-url-template = "https://github.com/loomio/loomio-docs/edit/main/user_manual/{path}"
site-url = "/en/user_manual/"

[output.html.redirect]
"privacy" = "/en/policy/privacy"
